---
title: "thesis purchase"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(meta)
library(metafor)
library(metadat)
library(haven)
library(writexl)
library(openxlsx)
library(dplyr)
library(stringr)
options(scipen = 999)
```

```{r}
## Load datasets and  for purchase 
data_purchase <- read.xlsx("appliance_purchase.xlsx")
```

```{r}
## Subset dataset for each appliance and intervention in purchase

data_purchase <- data_purchase %>% 
              mutate(Intervention = case_when(feedback == 1 ~ "Feedback",
                                              information == 1 ~ "Information",
                                              rebate == 1 ~ "Rebate",
                                              label == 1 ~ "Label", 
                                                tax_credit == 1 ~ "Tax"))

#Feedback and Washing Machine

data_purchase_washing <- data_purchase %>% 
                  filter(washing_machine == 1)

data_purchase_dishwasher <- data_purchase %>% 
                  filter(diswasher == 1)

data_purchase_refrigerator <- data_purchase %>% 
                  filter(refrigerator == 1)

data_purchase_heat_pump <- data_purchase %>% 
                  filter(heat_pump == 1)

data_purchase_lighting <- data_purchase %>% 
                  filter(lighting == 1)

data_purchase_water <- data_purchase %>% 
                  filter(water_heater == 1)

data_purchase_air <- data_purchase %>% 
                  filter(air_conditioning == 1)

data_purchase_tv <- data_purchase %>% 
                  filter(tv == 1)

```

```{r}
## creating matrix of appliance and intervention

##washing machine and all interventions
data_purchase_washing_label <- data_purchase_washing %>% 
                           filter(label ==1)

data_purchase_washing_rebate <- data_purchase_washing %>% 
                           filter(rebate ==1)

data_purchase_washing_information <- data_purchase_washing %>% 
                           filter(information ==1)


##dishwasher / interventions

data_purchase_dishwasher_information <- data_purchase_dishwasher %>% 
                                 filter(information == 1)

data_purchase_dishwasher_rebate <- data_purchase_dishwasher %>% 
                                 filter(rebate == 1)

##refrigerator

data_purchase_refrigerator_information <- data_purchase_refrigerator %>% 
                                 filter(information == 1)

data_purchase_refrigerator_rebate <- data_purchase_refrigerator %>% 
                                 filter(rebate == 1)

data_purchase_refrigerator_label <- data_purchase_refrigerator %>% 
                                 filter(label == 1)



##lighting
data_purchase_lighting_information <- data_purchase_lighting %>% 
                                 filter(information == 1)

data_purchase_lighting_label <- data_purchase_lighting %>% 
                                 filter(label == 1)
##air con
data_purchase_air_information <- data_purchase_air %>% 
                                 filter(information == 1)
data_purchase_air_label <- data_purchase_air %>% 
                                 filter(label == 1)
data_purchase_air_rebate <- data_purchase_air %>% 
                                 filter(rebate == 1)

##TV
data_purchase_tv_label <- data_purchase_tv %>% 
                                 filter(label == 1)

```


```{r}
## figure out metagen from meta package

##washing machine
m.gen_purchase_washing <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_washing,
                 studlab = Authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot 
png(file = "forestplot_washing_p.png", width = 5000, height = 3500, res = 500)

forest.meta(m.gen_purchase_washing,
           leftcols = c("Authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
dev.off()
```

```{r}
##dishwasher 
m.gen_purchase_dishwasher <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_dishwasher,
                 studlab = Authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 backtransf = F,
                 )

## forest plot 
png(file = "forestplot_dishwasher_p.png", width = 5000, height = 2450, res = 500)

forest.meta(m.gen_purchase_dishwasher,
           leftcols = c("Authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
dev.off()
```


```{r}
##refrigerator
m.gen_purchase_refrigerator <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_refrigerator,
                 studlab = Authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 backtransf = F,
                 )

## forest plot 
png(file = "forestplot_refrigerator_p.png", width = 5000, height = 3800, res = 500)

forest.meta(m.gen_purchase_refrigerator,
           leftcols = c("Authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

dev.off()
```


```{r}
##heatpump
m.gen_purchase_heat_pump <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_heat_pump,
                 studlab = Authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 backtransf = F,
                 )

## forest plot 
png(file = "forestplot_heatpump_p.png", width = 5000, height = 2000, res = 500)

forest.meta(m.gen_purchase_heat_pump,
           leftcols = c("Authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
dev.off()
```


```{r}
##lighting
m.gen_purchase_lighting <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_lighting,
                 studlab = Authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 backtransf = F,
                 )

## forest plot 
png(file = "forestplot_lighting.p.png", width = 5000, height = 2000, res = 500)

forest.meta(m.gen_purchase_lighting,
           leftcols = c("Authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
dev.off()
```


```{r}
##airconditioning
m.gen_purchase_air <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_air,
                 studlab = Authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 backtransf = F,
                 )

## forest plot 
png(file = "forestplot_air_p.png", width = 5000, height = 2000, res = 500)

forest.meta(m.gen_purchase_air,
           leftcols = c("Authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

dev.off()
```

```{r}
##TV
m.gen_purchase_tv <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_purchase_tv,
                 studlab = Authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 backtransf = F,
                 )

## forest plot 
png(file = "forestplot_tv_p.png", width = 5000, height = 2300, res = 500)

forest.meta(m.gen_purchase_tv,
           leftcols = c("Authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

dev.off()
```

```{r}
########Pooled effect sizes (generic inverse variance pooling method)

###washing machine
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_washing,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

###referigerator
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_refrigerator,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

##dishwasher
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_dishwasher,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)


##heatpump
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_heat_pump,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)


##air conditioning
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_air,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

## lighting
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_lighting,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

## tv
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_tv,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)
```

```{r}
##### Pooled values for appliance and intervention

###Washing Machine
## label and washing machine

metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_washing_label,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

## reabte and washing machine
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_washing_rebate,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)
## info and washing machine
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_washing_information,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)
```

```{r}
###Dishwasher
## info and dihswasher

metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_dishwasher_information,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

## rebate and dishwasher
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_dishwasher_rebate,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)
```


```{r}
###Refrigerator
## info and ref

metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_refrigerator_information,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

## label and ref
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_refrigerator_label,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

## rebate and ref
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_refrigerator_rebate,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)
```



```{r}
###lighting

## info and light
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_lighting_information,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

## feedback and lighting
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_lighting_label,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)
```

```{r}
### air con

## air & feedback
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_air_label,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

## info and air
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_air_information,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

## rebate and air
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_purchase_air_rebate,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)
```
