---
title: "thesis usage"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(meta)
library(metafor)
library(metadat)
library(haven)
library(writexl)
library(openxlsx)
library(dplyr)
library(stringr)
options(scipen = 999)
```

```{r}
## Load datasets  for usage 
data_usage <- read.xlsx("appliance_usage.xlsx")
```

```{r}
## Subset dataset for each appliance and intervention in Usage

data_usage <- data_usage %>% 
              mutate(Intervention = case_when(feedback == 1 ~ "Feedback",
                                              information == 1 ~ "Information",
                                              rebate == 1 ~ "Rebate",
                                              label == 1 ~ "Label", 
                                                tax_credit == 1 ~ "Tax"))

#Feedback and Washing Machine

data_usage_washing <- data_usage %>% 
                  filter(washing_machine == 1)

data_usage_dishwasher <- data_usage %>% 
                  filter(diswasher == 1)

data_usage_refrigerator <- data_usage %>% 
                  filter(refrigerator == 1)

data_usage_heat_pump <- data_usage %>% 
                  filter(heat_pump == 1)

data_usage_lighting <- data_usage %>% 
                  filter(lighting == 1)

data_usage_water <- data_usage %>% 
                  filter(water_heater == 1)

data_usage_air <- data_usage %>% 
                  filter(air_conditioning == 1)
```

```{r}
## creating matrix of appliance and intervention

##washing machine and all interventions
data_usage_washing_label <- data_usage_washing %>% 
                           filter(label ==1)

data_usage_washing_rebate <- data_usage_washing %>% 
                           filter(rebate ==1)

##dishwasher / interventions

data_usage_dishwasher_information <- data_usage_dishwasher %>% 
                                 filter(information == 1)

data_usage_dishwasher_rebate <- data_usage_dishwasher %>% 
                                 filter(rebate == 1)

##refrigerator

data_usage_refrigerator_information <- data_usage_refrigerator %>% 
                                 filter(information == 1)

data_usage_refrigerator_rebate <- data_usage_refrigerator %>% 
                                 filter(rebate == 1)

data_usage_refrigerator_label <- data_usage_refrigerator %>% 
                                 filter(label == 1)

##heatpump
data_usage_heat_pump_information <- data_usage_heat_pump %>% 
                                 filter(information == 1)

data_usage_heat_pump_feedback <- data_usage_heat_pump %>% 
                                 filter(feedback == 1)

data_usage_heat_pump_rebate <- data_usage_heat_pump %>% 
                                 filter(rebate == 1)

##lighting
data_usage_lighting_information <- data_usage_lighting %>% 
                                 filter(information == 1)

data_usage_lighting_feedback <- data_usage_lighting %>% 
                                 filter(feedback == 1)
##air con
data_usage_air_information <- data_usage_air %>% 
                                 filter(information == 1)
data_usage_air_feedback <- data_usage_air %>% 
                                 filter(feedback == 1)
data_usage_air_rebate <- data_usage_air %>% 
                                 filter(rebate == 1)
```

```{r}
##washing machine
m.gen_usage_washing <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_usage_washing,
                 studlab = Authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of usage

png(file = "forestplot_washing.png", width = 5000, height = 2000, res = 500)
forest.meta(m.gen_usage_washing,
           leftcols = c("Authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")
         

dev.off()
```


```{r}
##dishwasher 
m.gen_usage_dishwasher <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_usage_dishwasher,
                 studlab = Authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of usage
png(file = "forestplot_dishwasher.png", width = 5000, height = 2000, res = 500)
forest.meta(m.gen_usage_dishwasher,
           leftcols = c("Authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

dev.off()
```


```{r}
##refrigerator
m.gen_usage_refrigerator <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_usage_refrigerator,
                 studlab = Authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of usage

png(file = "forestplot_refrigerator_u.png", width = 5000, height = 2200, res = 500)
forest.meta(m.gen_usage_refrigerator,
           leftcols = c("Authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

dev.off()
           
```

```{r}
##heatpump
m.gen_usage_heat_pump <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_usage_heat_pump,
                 studlab = Authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of usage
png(file = "forestplot_heatpump_u.png", width = 5000, height = 1800, res = 500)
forest.meta(m.gen_usage_heat_pump,
           leftcols = c("Authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

dev.off()
```


```{r}
##lighting
m.gen_usage_lighting <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_usage_lighting,
                 studlab = Authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of usage

png(file = "forestplot_lighting_u.png", width = 5000, height = 1500, res = 500)

forest.meta(m.gen_usage_lighting,
           leftcols = c("Authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

dev.off()

```


```{r}
##airconditioning
m.gen_usage_air <- metagen(TE = z_value,
                 seTE = z_variance,
                 data = data_usage_air,
                 studlab = Authors,
                 sm = "ZCOR",
                 fixed = FALSE,
                 random = TRUE,
                 backtransf = F,
                 )

## forest plot of usage

png(file = "forestplot_air_u.png", width = 5500, height = 2600, res = 500)

forest.meta(m.gen_usage_air,
           leftcols = c("Authors", "Intervention"),
           digits =6,
           col.random = "Red",
           xlab = "Effect Sizes",
           col.square = "Blue")

dev.off()
```

```{r}
########Pooled effect sizes (generic inverse variance pooling method)

###washing machine
pooled_washing <- metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_washing,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)
pooled_washing
##studies 9
## r = -0.0001

###referigerator
pooled_refrigerator <- metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_refrigerator,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)
pooled_refrigerator
##dishwasher
pooled_dishwasher <- metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_dishwasher,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)
pooled_dishwasher

##heatpump

pooled_heatpump <- metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_heat_pump,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

pooled_heatpump

##air conditioning
pooled_airconditioning <- metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_air,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

pooled_airconditioning

## lighting
pooled_lighting <- metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_lighting,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

pooled_lighting
```

```{r}
##### Pooled values for appliance and intervention

###Washing Machine
## label and washing machine

metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_washing_label,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)
## reabte and washing machine
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_washing_rebate,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)
```

```{r}
###Dishwasher
## info and dihswasher

metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_dishwasher_information,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)
## rebate and dishwasher
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_dishwasher_rebate,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)
```


```{r}
###Refrigerator
## info and ref

metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_refrigerator_information,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

## label and ref
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_refrigerator_label,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

## rebate and ref
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_refrigerator_rebate,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)
```

```{r}
###heat pump

##heat pump & info
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_heat_pump_information,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

## feedback and heatpump
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_heat_pump_feedback,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

## rebate and heatpump
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_heat_pump_rebate,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)
```

```{r}
###lighting

## info and light
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_lighting_information,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

## feedback and lighting
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_lighting_feedback,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)
```

```{r}
### air con

## air & feedback
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_air_feedback,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

## info and air
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_air_information,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)

## rebate and air
metacor(cor = r_effect_size_obsversation,
        n = total_observations,
        data = data_usage_air_rebate,
        fixed =  F,
        random = T,
        method.tau = "REML",
        hakn = T)
```

```{r}
####ggplot of just the pooled effect of each of the appliances

cohort <- as.character(c("Washing Machine", "Refrigerator","Dishwasher", "Heat Pump","Air Conditioning", "Lighting" ))
beta <-  as.numeric(c(-0.0001, 0.0040, -0.0007, 0.0009,-0.0,-0.0075 ))
lower95 <- as.numeric(c(-0.0003, 0.0004, -0.0034, -0.0023,-0.0001, -0.0111))
upper95 <- as.numeric(c(0.0001,0.0076,0.0019, 0.0042, 0.0001, -0.0039))
population <- as.numeric(c(9,11,7,7,13,4))
data_plot_usage <- as.data.frame(cbind(cohort, beta ,lower95,upper95,population))

ggplot(data=data_plot_usage,aes(x=beta,y=cohort))+
        geom_point(aes(size=population))+
        geom_errorbarh(aes(xmin=lower95,xmax=upper95))+
        theme_minimal()

```

